apiVersion: v1
kind: Service
metadata:
  name: carbon-frontend-svc
  labels:
    app: carbon-frontend-dp
spec:
  ports:
  - port: 19002
    targetPort: 80
    protocol: TCP
  selector:
    app: carbon-frontend-dp
