apiVersion: apps/v1
kind: Deployment
metadata:
  name: carbon-frontend-dp
  labels:
    app: carbon-frontend-dp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: carbon-frontend-dp
  template:
    metadata:
      labels:
        app: carbon-frontend-dp
    spec:
      imagePullSecrets:
       - name: regscaleway
      volumes:
        - configMap:
            name: carbon-frontend-cm
          name: config-js
      containers:
      - name: carbon-frontend-dp
        image: rg.fr-par.scw.cloud/carbon/carbon-frontend:develop
        imagePullPolicy: Always
        volumeMounts:
          - mountPath: /usr/share/nginx/html/config.js
            name: config-js
            subPath: config.js
