"""add offset log

Revision ID: 09af7e2c34e1
Revises: fce99714b043
Create Date: 2023-02-03 11:07:24.535041

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '09af7e2c34e1'
down_revision = 'fce99714b043'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('offset_logs',
                    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
                    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
                    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
                    sa.Column('unit_price', sa.Numeric(precision=10, scale=1), nullable=False),
                    sa.Column('unit_count', sa.Integer(), nullable=False),
                    sa.Column('action', sa.Text(), nullable=False),
                    sa.Column('source_offset_id', postgresql.UUID(as_uuid=True), nullable=False),
                    sa.Column('target_offset_id', postgresql.UUID(as_uuid=True), nullable=False),
                    sa.Column('company_id', postgresql.UUID(as_uuid=True), nullable=False),
                    sa.ForeignKeyConstraint(['company_id'], ['carbon.companies.id'], ondelete='CASCADE'),
                    sa.ForeignKeyConstraint(['source_offset_id'], ['carbon.offsets.id'], ondelete='CASCADE'),
                    sa.ForeignKeyConstraint(['target_offset_id'], ['carbon.offsets.id'], ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint('id'),
                    schema='carbon'
                    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('offset_logs', schema='carbon')
    # ### end Alembic commands ###
