"""add project image

Revision ID: 5de28db22aa3
Revises: 5e5d0e65683b
Create Date: 2023-01-23 20:15:31.787421

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '5de28db22aa3'
down_revision = '5e5d0e65683b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('image_uri', sa.Text(), nullable=True), schema='carbon')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'image_uri', schema='carbon')
    # ### end Alembic commands ###
