"""add_moderator

Revision ID: 5e5d0e65683b
Revises: 94ccd2b39ea9
Create Date: 2023-01-18 21:08:47.037918

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '5e5d0e65683b'
down_revision = '94ccd2b39ea9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('moderators',
                    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
                    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
                    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
                    sa.Column('phone_number', sa.Text(), nullable=False),
                    sa.Column('user_id', postgresql.UUID(as_uuid=True), nullable=False),
                    sa.ForeignKeyConstraint(['user_id'], ['carbon.users.id'], ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint('id'),
                    schema='carbon'
                    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('moderators', schema='carbon')
    # ### end Alembic commands ###
