"""add project image aspect ratio

Revision ID: 7fa57b2b7b65
Revises: df1826a30bf4
Create Date: 2023-02-20 16:12:19.601247

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '7fa57b2b7b65'
down_revision = 'df1826a30bf4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('image_aspect_ratio', sa.Float(), nullable=True), schema='carbon')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'image_aspect_ratio', schema='carbon')
    # ### end Alembic commands ###
