"""add transactions

Revision ID: c1e7869df2f2
Revises: 7fa57b2b7b65
Create Date: 2023-02-23 15:14:40.532365

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'c1e7869df2f2'
down_revision = '7fa57b2b7b65'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transaction_statuses',
                    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
                    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
                    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
                    sa.Column('name', sa.Text(), nullable=False),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('name'),
                    schema='carbon'
                    )
    op.create_table('transactions',
                    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
                    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
                    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
                    sa.Column('unit_count', sa.Integer(), nullable=False),
                    sa.Column('unit_price', sa.Numeric(precision=10, scale=1), nullable=False),
                    sa.Column('transaction_status_id', postgresql.UUID(as_uuid=True), nullable=False),
                    sa.Column('offset_id', postgresql.UUID(as_uuid=True), nullable=False),
                    sa.Column('company_id', postgresql.UUID(as_uuid=True), nullable=False),
                    sa.ForeignKeyConstraint(['company_id'], ['carbon.companies.id'], ondelete='CASCADE'),
                    sa.ForeignKeyConstraint(['offset_id'], ['carbon.offsets.id'], ondelete='CASCADE'),
                    sa.ForeignKeyConstraint(['transaction_status_id'], ['carbon.transaction_statuses.id'],
                                            ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint('id'),
                    schema='carbon'
                    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transactions', schema='carbon')
    op.drop_table('transaction_statuses', schema='carbon')
    # ### end Alembic commands ###
