"""AddOffsetUnit

Revision ID: fce99714b043
Revises: 5de28db22aa3
Create Date: 2023-01-23 21:52:26.227223

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'fce99714b043'
down_revision = '5de28db22aa3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('offset_units',
                    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
                    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
                    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
                    sa.Column('offset_id', postgresql.UUID(as_uuid=True), nullable=False),
                    sa.ForeignKeyConstraint(['offset_id'], ['carbon.offsets.id'], ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint('id'),
                    schema='carbon'
                    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('offset_units', schema='carbon')
    # ### end Alembic commands ###
